# coding: utf-8
"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from klarna_checkout_python_sdk.client_custom import ClientCustom
from klarna_checkout_python_sdk.configuration import Configuration
from klarna_checkout_python_sdk.api_client import ApiClient
from klarna_checkout_python_sdk.type_util import copy_signature
from klarna_checkout_python_sdk.apis.tags.order_api import OrderApi



class KlarnaCheckout(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.order: OrderApi = OrderApi(api_client)
