# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Address(BaseModel):
    # Title.<p>Valid values for UK:</p><ul><li><em>Mr</em></li><li><em>Ms</em></li><li><em>Mrs</em></li><li><em>Miss</em></li></ul><p>Valid values for DACH:</p><ul><li><em>Herr</em></li><li><em>Frau</em></li></ul><p>Valid values for NL:</p><ul><li><em>Dhr.</em></li><li><em>Mevr.</em></li></ul>
    title: typing.Optional[str] = Field(None, alias='title')

    # Given name.
    given_name: typing.Optional[str] = Field(None, alias='given_name')

    # Family name.
    family_name: typing.Optional[str] = Field(None, alias='family_name')

    # E-mail address.
    email: typing.Optional[str] = Field(None, alias='email')

    # Street address, first line. (Street name and number)
    street_address: typing.Optional[str] = Field(None, alias='street_address')

    # Street address, second line. (Apartment number, suite, etc.)
    street_address2: typing.Optional[str] = Field(None, alias='street_address2')

    # Street name. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetNumber</b>.
    street_name: typing.Optional[str] = Field(None, alias='street_name')

    # Street number. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetName</b>.
    street_number: typing.Optional[str] = Field(None, alias='street_number')

    # House extension. Only applicable in NL
    house_extension: typing.Optional[str] = Field(None, alias='house_extension')

    # Postal/post code.
    postal_code: typing.Optional[str] = Field(None, alias='postal_code')

    # City.
    city: typing.Optional[str] = Field(None, alias='city')

    # State or Region.
    region: typing.Optional[str] = Field(None, alias='region')

    # Phone number.
    phone: typing.Optional[str] = Field(None, alias='phone')

    # ISO 3166 alpha-2. Country.
    country: typing.Optional[str] = Field(None, alias='country')

    # Care of.
    care_of: typing.Optional[str] = Field(None, alias='care_of')
    class Config:
        arbitrary_types_allowed = True
