# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Dimensions(BaseModel):
    # The product's height as used in the merchant's webshop. Non-negative. Measured in millimeters.
    height: typing.Optional[int] = Field(None, alias='height')

    # The product's width as used in the merchant's webshop. Non-negative. Measured in millimeters.
    width: typing.Optional[int] = Field(None, alias='width')

    # The product's length as used in the merchant's webshop. Non-negative. Measured in millimeters.
    length: typing.Optional[int] = Field(None, alias='length')
    class Config:
        arbitrary_types_allowed = True
