# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DiscountLine(BaseModel):
    # Descriptive name of discount
    name: str = Field(alias='name')

    # Non-negative number. Quantity of the discount line item.
    quantity: int = Field(alias='quantity')

    # Minor units. Includes tax, excludes discount. (Must be non-positive).  Example: -100 Euros should be -10000.
    unit_price: int = Field(alias='unit_price')

    # Non-negative value. The percentage value is represented with two implicit decimals. (max 10000)  Example: 25% should be 2500.
    tax_rate: int = Field(alias='tax_rate')

    # Minor units. Includes tax and discount.   Example: -25 euros should be -2500 Value = (quantity x unit_price). (Must be non-positive)
    total_amount: int = Field(alias='total_amount')

    # Must be within ±1 of total_amount - total_amount \\* 10000 / (10000 + tax_rate). Should be non-positive
    total_tax_amount: int = Field(alias='total_tax_amount')

    # The CRM reference to the gift-card that was entered by the user
    reference: typing.Optional[str] = Field(None, alias='reference')

    # The gift-card number that was entered by the user
    merchant_data: typing.Optional[str] = Field(None, alias='merchant_data')
    class Config:
        arbitrary_types_allowed = True
