# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from klarna_checkout_python_sdk.pydantic.merchant_requested_checkbox import MerchantRequestedCheckbox

class MerchantRequested(BaseModel):
    # Informs whether the additional_checkbox is checked or not, when applicable.
    additional_checkbox: typing.Optional[bool] = Field(None, alias='additional_checkbox')

    # Informs whether the additional_checkboxes is checked or not, when applicable.
    additional_checkboxes: typing.Optional[typing.List[MerchantRequestedCheckbox]] = Field(None, alias='additional_checkboxes')
    class Config:
        arbitrary_types_allowed = True
