# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from klarna_checkout_python_sdk.pydantic.address import Address

class PickupLocationV1(BaseModel):
    # Id
    id: typing.Optional[str] = Field(None, alias='id')

    # Name of the location
    name: typing.Optional[str] = Field(None, alias='name')

    address: typing.Optional[Address] = Field(None, alias='address')
    class Config:
        arbitrary_types_allowed = True
