# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from klarna_checkout_python_sdk.pydantic.delivery_details_v1 import DeliveryDetailsV1
from klarna_checkout_python_sdk.pydantic.selected_addon import SelectedAddon

class ShippingOption(BaseModel):
    # id
    id: str = Field(alias='id')

    # Name.
    name: str = Field(alias='name')

    # Price including tax.
    price: int = Field(alias='price')

    # Tax amount.
    tax_amount: int = Field(alias='tax_amount')

    # Non-negative. In percent, two implicit decimals. I.e 2500 = 25%.
    tax_rate: int = Field(alias='tax_rate')

    # Description.
    description: typing.Optional[str] = Field(None, alias='description')

    # Promotion name. To be used if this shipping option is promotional.
    promo: typing.Optional[str] = Field(None, alias='promo')

    # If true, this option will be preselected when checkout loads. Default: false
    preselected: typing.Optional[bool] = Field(None, alias='preselected')

    # Shipping method. Possible values:<ul><li>PickUpStore</li><li>Home</li><li>BoxReg</li><li>BoxUnreg</li><li>PickUpPoint</li><li>Own</li><li>Postal</li><li>DHLPackstation</li><li>Digital</li></ul> If DHLPackstation is selected the correct form will be displayed.
    shipping_method: typing.Optional[str] = Field(None, alias='shipping_method')

    delivery_details: typing.Optional[DeliveryDetailsV1] = Field(None, alias='delivery_details')

    # TMS reference. Required to map completed orders to shipments reserved in TMS.
    tms_reference: typing.Optional[str] = Field(None, alias='tms_reference')

    selected_addons: typing.Optional[typing.List[SelectedAddon]] = Field(None, alias='selected_addons')
    class Config:
        arbitrary_types_allowed = True
