# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from klarna_checkout_python_sdk import schemas  # noqa: F401


class Address(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
            given_name = schemas.StrSchema
            family_name = schemas.StrSchema
            email = schemas.StrSchema
            street_address = schemas.StrSchema
            street_address2 = schemas.StrSchema
            street_name = schemas.StrSchema
            street_number = schemas.StrSchema
            house_extension = schemas.StrSchema
            postal_code = schemas.StrSchema
            city = schemas.StrSchema
            region = schemas.StrSchema
            phone = schemas.StrSchema
            country = schemas.StrSchema
            care_of = schemas.StrSchema
            __annotations__ = {
                "title": title,
                "given_name": given_name,
                "family_name": family_name,
                "email": email,
                "street_address": street_address,
                "street_address2": street_address2,
                "street_name": street_name,
                "street_number": street_number,
                "house_extension": house_extension,
                "postal_code": postal_code,
                "city": city,
                "region": region,
                "phone": phone,
                "country": country,
                "care_of": care_of,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["given_name"]) -> MetaOapg.properties.given_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["family_name"]) -> MetaOapg.properties.family_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["street_address"]) -> MetaOapg.properties.street_address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["street_address2"]) -> MetaOapg.properties.street_address2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["street_name"]) -> MetaOapg.properties.street_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["street_number"]) -> MetaOapg.properties.street_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["house_extension"]) -> MetaOapg.properties.house_extension: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["postal_code"]) -> MetaOapg.properties.postal_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["city"]) -> MetaOapg.properties.city: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country"]) -> MetaOapg.properties.country: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["care_of"]) -> MetaOapg.properties.care_of: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "given_name", "family_name", "email", "street_address", "street_address2", "street_name", "street_number", "house_extension", "postal_code", "city", "region", "phone", "country", "care_of", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["given_name"]) -> typing.Union[MetaOapg.properties.given_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["family_name"]) -> typing.Union[MetaOapg.properties.family_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["street_address"]) -> typing.Union[MetaOapg.properties.street_address, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["street_address2"]) -> typing.Union[MetaOapg.properties.street_address2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["street_name"]) -> typing.Union[MetaOapg.properties.street_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["street_number"]) -> typing.Union[MetaOapg.properties.street_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["house_extension"]) -> typing.Union[MetaOapg.properties.house_extension, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["postal_code"]) -> typing.Union[MetaOapg.properties.postal_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["city"]) -> typing.Union[MetaOapg.properties.city, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> typing.Union[MetaOapg.properties.region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> typing.Union[MetaOapg.properties.phone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country"]) -> typing.Union[MetaOapg.properties.country, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["care_of"]) -> typing.Union[MetaOapg.properties.care_of, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "given_name", "family_name", "email", "street_address", "street_address2", "street_name", "street_number", "house_extension", "postal_code", "city", "region", "phone", "country", "care_of", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        given_name: typing.Union[MetaOapg.properties.given_name, str, schemas.Unset] = schemas.unset,
        family_name: typing.Union[MetaOapg.properties.family_name, str, schemas.Unset] = schemas.unset,
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        street_address: typing.Union[MetaOapg.properties.street_address, str, schemas.Unset] = schemas.unset,
        street_address2: typing.Union[MetaOapg.properties.street_address2, str, schemas.Unset] = schemas.unset,
        street_name: typing.Union[MetaOapg.properties.street_name, str, schemas.Unset] = schemas.unset,
        street_number: typing.Union[MetaOapg.properties.street_number, str, schemas.Unset] = schemas.unset,
        house_extension: typing.Union[MetaOapg.properties.house_extension, str, schemas.Unset] = schemas.unset,
        postal_code: typing.Union[MetaOapg.properties.postal_code, str, schemas.Unset] = schemas.unset,
        city: typing.Union[MetaOapg.properties.city, str, schemas.Unset] = schemas.unset,
        region: typing.Union[MetaOapg.properties.region, str, schemas.Unset] = schemas.unset,
        phone: typing.Union[MetaOapg.properties.phone, str, schemas.Unset] = schemas.unset,
        country: typing.Union[MetaOapg.properties.country, str, schemas.Unset] = schemas.unset,
        care_of: typing.Union[MetaOapg.properties.care_of, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Address':
        return super().__new__(
            cls,
            *args,
            title=title,
            given_name=given_name,
            family_name=family_name,
            email=email,
            street_address=street_address,
            street_address2=street_address2,
            street_name=street_name,
            street_number=street_number,
            house_extension=house_extension,
            postal_code=postal_code,
            city=city,
            region=region,
            phone=phone,
            country=country,
            care_of=care_of,
            _configuration=_configuration,
            **kwargs,
        )
