# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from klarna_checkout_python_sdk import schemas  # noqa: F401


class OrderLine(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "quantity",
            "total_amount",
            "name",
            "total_tax_amount",
            "unit_price",
            "tax_rate",
        }
        
        class properties:
            
            
            class name(
                schemas.StrSchema
            ):
                pass
            
            
            class quantity(
                schemas.Int64Schema
            ):
                pass
            
            
            class unit_price(
                schemas.Int64Schema
            ):
                pass
            
            
            class tax_rate(
                schemas.Int64Schema
            ):
                pass
            
            
            class total_amount(
                schemas.Int64Schema
            ):
                pass
            total_tax_amount = schemas.Int64Schema
            type = schemas.StrSchema
            
            
            class reference(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def subscription() -> typing.Type['Subscription']:
                return Subscription
            quantity_unit = schemas.StrSchema
            
            
            class total_discount_amount(
                schemas.Int64Schema
            ):
                pass
            
            
            class merchant_data(
                schemas.StrSchema
            ):
                pass
            
            
            class product_url(
                schemas.StrSchema
            ):
                pass
            
            
            class image_url(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def product_identifiers() -> typing.Type['ProductIdentifiers']:
                return ProductIdentifiers
        
            @staticmethod
            def shipping_attributes() -> typing.Type['ShippingAttributes']:
                return ShippingAttributes
            __annotations__ = {
                "name": name,
                "quantity": quantity,
                "unit_price": unit_price,
                "tax_rate": tax_rate,
                "total_amount": total_amount,
                "total_tax_amount": total_tax_amount,
                "type": type,
                "reference": reference,
                "subscription": subscription,
                "quantity_unit": quantity_unit,
                "total_discount_amount": total_discount_amount,
                "merchant_data": merchant_data,
                "product_url": product_url,
                "image_url": image_url,
                "product_identifiers": product_identifiers,
                "shipping_attributes": shipping_attributes,
            }
    
    quantity: MetaOapg.properties.quantity
    total_amount: MetaOapg.properties.total_amount
    name: MetaOapg.properties.name
    total_tax_amount: MetaOapg.properties.total_tax_amount
    unit_price: MetaOapg.properties.unit_price
    tax_rate: MetaOapg.properties.tax_rate
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tax_rate"]) -> MetaOapg.properties.tax_rate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_amount"]) -> MetaOapg.properties.total_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_tax_amount"]) -> MetaOapg.properties.total_tax_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reference"]) -> MetaOapg.properties.reference: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscription"]) -> 'Subscription': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity_unit"]) -> MetaOapg.properties.quantity_unit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_discount_amount"]) -> MetaOapg.properties.total_discount_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchant_data"]) -> MetaOapg.properties.merchant_data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_url"]) -> MetaOapg.properties.product_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image_url"]) -> MetaOapg.properties.image_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_identifiers"]) -> 'ProductIdentifiers': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipping_attributes"]) -> 'ShippingAttributes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "quantity", "unit_price", "tax_rate", "total_amount", "total_tax_amount", "type", "reference", "subscription", "quantity_unit", "total_discount_amount", "merchant_data", "product_url", "image_url", "product_identifiers", "shipping_attributes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tax_rate"]) -> MetaOapg.properties.tax_rate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_amount"]) -> MetaOapg.properties.total_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_tax_amount"]) -> MetaOapg.properties.total_tax_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reference"]) -> typing.Union[MetaOapg.properties.reference, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscription"]) -> typing.Union['Subscription', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity_unit"]) -> typing.Union[MetaOapg.properties.quantity_unit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_discount_amount"]) -> typing.Union[MetaOapg.properties.total_discount_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchant_data"]) -> typing.Union[MetaOapg.properties.merchant_data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_url"]) -> typing.Union[MetaOapg.properties.product_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image_url"]) -> typing.Union[MetaOapg.properties.image_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_identifiers"]) -> typing.Union['ProductIdentifiers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipping_attributes"]) -> typing.Union['ShippingAttributes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "quantity", "unit_price", "tax_rate", "total_amount", "total_tax_amount", "type", "reference", "subscription", "quantity_unit", "total_discount_amount", "merchant_data", "product_url", "image_url", "product_identifiers", "shipping_attributes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        quantity: typing.Union[MetaOapg.properties.quantity, decimal.Decimal, int, ],
        total_amount: typing.Union[MetaOapg.properties.total_amount, decimal.Decimal, int, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        total_tax_amount: typing.Union[MetaOapg.properties.total_tax_amount, decimal.Decimal, int, ],
        unit_price: typing.Union[MetaOapg.properties.unit_price, decimal.Decimal, int, ],
        tax_rate: typing.Union[MetaOapg.properties.tax_rate, decimal.Decimal, int, ],
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        reference: typing.Union[MetaOapg.properties.reference, str, schemas.Unset] = schemas.unset,
        subscription: typing.Union['Subscription', schemas.Unset] = schemas.unset,
        quantity_unit: typing.Union[MetaOapg.properties.quantity_unit, str, schemas.Unset] = schemas.unset,
        total_discount_amount: typing.Union[MetaOapg.properties.total_discount_amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        merchant_data: typing.Union[MetaOapg.properties.merchant_data, str, schemas.Unset] = schemas.unset,
        product_url: typing.Union[MetaOapg.properties.product_url, str, schemas.Unset] = schemas.unset,
        image_url: typing.Union[MetaOapg.properties.image_url, str, schemas.Unset] = schemas.unset,
        product_identifiers: typing.Union['ProductIdentifiers', schemas.Unset] = schemas.unset,
        shipping_attributes: typing.Union['ShippingAttributes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OrderLine':
        return super().__new__(
            cls,
            *args,
            quantity=quantity,
            total_amount=total_amount,
            name=name,
            total_tax_amount=total_tax_amount,
            unit_price=unit_price,
            tax_rate=tax_rate,
            type=type,
            reference=reference,
            subscription=subscription,
            quantity_unit=quantity_unit,
            total_discount_amount=total_discount_amount,
            merchant_data=merchant_data,
            product_url=product_url,
            image_url=image_url,
            product_identifiers=product_identifiers,
            shipping_attributes=shipping_attributes,
            _configuration=_configuration,
            **kwargs,
        )

from klarna_checkout_python_sdk.model.product_identifiers import ProductIdentifiers
from klarna_checkout_python_sdk.model.shipping_attributes import ShippingAttributes
from klarna_checkout_python_sdk.model.subscription import Subscription
