# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import klarna_checkout_python_sdk
from klarna_checkout_python_sdk.paths.checkout_v3_orders_order_id import post
from klarna_checkout_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestCheckoutV3OrdersOrderId(ApiTestMixin, unittest.TestCase):
    """
    CheckoutV3OrdersOrderId unit test stubs
        Update an order
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
