# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAddress(TypedDict):
    pass

class OptionalAddress(TypedDict, total=False):
    # Title.<p>Valid values for UK:</p><ul><li><em>Mr</em></li><li><em>Ms</em></li><li><em>Mrs</em></li><li><em>Miss</em></li></ul><p>Valid values for DACH:</p><ul><li><em>Herr</em></li><li><em>Frau</em></li></ul><p>Valid values for NL:</p><ul><li><em>Dhr.</em></li><li><em>Mevr.</em></li></ul>
    title: str

    # Given name.
    given_name: str

    # Family name.
    family_name: str

    # E-mail address.
    email: str

    # Street address, first line. (Street name and number)
    street_address: str

    # Street address, second line. (Apartment number, suite, etc.)
    street_address2: str

    # Street name. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetNumber</b>.
    street_name: str

    # Street number. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetName</b>.
    street_number: str

    # House extension. Only applicable in NL
    house_extension: str

    # Postal/post code.
    postal_code: str

    # City.
    city: str

    # State or Region.
    region: str

    # Phone number.
    phone: str

    # ISO 3166 alpha-2. Country.
    country: str

    # Care of.
    care_of: str

class Address(RequiredAddress, OptionalAddress):
    pass
