# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAttachment(TypedDict):
    # The content of the extra merchant data which should be presented as a string inside this property. The body should be an object containing any of the keys and sub objects described below serialised to JSON. More information on that object can be found [here](https://docs.klarna.com/klarna-checkout/api/checkout-api/#tag/Attachment-Schema).
    body: str

    # The content type of the body. It is usually represented as \"application/vnd.klarna.internal.emd-v2+json\"
    content_type: str

class OptionalAttachment(TypedDict, total=False):
    pass

class Attachment(RequiredAttachment, OptionalAttachment):
    pass
