# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomer(TypedDict):
    pass

class OptionalCustomer(TypedDict, total=False):
    # The default supported value is 'person'. If B2B is enabled for the merchant, the value may be \"organization\".
    type: str

    # Customer’s gender - ‘male’ or ‘female’.
    gender: str

    # Customer’s date of birth. The format is ‘yyyy-mm-dd’. ISO 8601 date.
    date_of_birth: str

    # \"The organization's official registration id (organization number).  Note: Applicable only for B2B orders.\"
    organization_registration_id: str

    # Organization VAT ID. Only applies for b2b orders.
    vat_id: str

class Customer(RequiredCustomer, OptionalCustomer):
    pass
