# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from klarna_checkout_python_sdk.type.pickup_location_v1 import PickupLocationV1
from klarna_checkout_python_sdk.type.product_v1 import ProductV1
from klarna_checkout_python_sdk.type.timeslot_v1 import TimeslotV1

class RequiredDeliveryDetailsV1(TypedDict):
    pass

class OptionalDeliveryDetailsV1(TypedDict, total=False):
    # Carrier product name
    carrier: str

    product: ProductV1

    timeslot: TimeslotV1

    pickup_location: PickupLocationV1

class DeliveryDetailsV1(RequiredDeliveryDetailsV1, OptionalDeliveryDetailsV1):
    pass
