# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDiscountLine(TypedDict):
    # Descriptive name of discount
    name: str

    # Non-negative number. Quantity of the discount line item.
    quantity: int

    # Minor units. Includes tax, excludes discount. (Must be non-positive).  Example: -100 Euros should be -10000.
    unit_price: int

    # Non-negative value. The percentage value is represented with two implicit decimals. (max 10000)  Example: 25% should be 2500.
    tax_rate: int

    # Minor units. Includes tax and discount.   Example: -25 euros should be -2500 Value = (quantity x unit_price). (Must be non-positive)
    total_amount: int

    # Must be within ±1 of total_amount - total_amount \\* 10000 / (10000 + tax_rate). Should be non-positive
    total_tax_amount: int

class OptionalDiscountLine(TypedDict, total=False):
    # The CRM reference to the gift-card that was entered by the user
    reference: str

    # The gift-card number that was entered by the user
    merchant_data: str

class DiscountLine(RequiredDiscountLine, OptionalDiscountLine):
    pass
