# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from klarna_checkout_python_sdk.type.address import Address
from klarna_checkout_python_sdk.type.attachment import Attachment
from klarna_checkout_python_sdk.type.customer import Customer
from klarna_checkout_python_sdk.type.discount_line import DiscountLine
from klarna_checkout_python_sdk.type.gui import Gui
from klarna_checkout_python_sdk.type.merchant_requested import MerchantRequested
from klarna_checkout_python_sdk.type.merchant_urls import MerchantUrls
from klarna_checkout_python_sdk.type.options import Options
from klarna_checkout_python_sdk.type.order_billing_countries import OrderBillingCountries
from klarna_checkout_python_sdk.type.order_line import OrderLine
from klarna_checkout_python_sdk.type.order_shipping_countries import OrderShippingCountries
from klarna_checkout_python_sdk.type.order_tags import OrderTags
from klarna_checkout_python_sdk.type.payment_provider import PaymentProvider
from klarna_checkout_python_sdk.type.shipping_option import ShippingOption

class RequiredOrder(TypedDict):
    # The purchase country of the merchant's store. The format to be used is ISO 3166 alpha-2. Eg: GB, SE, DE, US, etc.   Note: purchase country and currency need to match the defined merchant configuration. For global configuration read this https://docs.klarna.com/klarna-checkout/popular-use-cases/selling-to-multiple-countries/
    purchase_country: str

    # The purchase currency of the merchant's store. The format to be used is ISO 4217. Eg: USD, EUR, SEK, GBP, etc.  Note: purchase country and currency need to match the defined merchant configuration. For global configuration read this https://docs.klarna.com/klarna-checkout/popular-use-cases/selling-to-multiple-countries/
    purchase_currency: str

    # Used to define the language and region of the customer. RFC 1766 customer's locale.
    locale: str

    # Total amount of the order including tax and any available discounts. The value should be in non-negative minor units.  Example: 25 Euros should be 2500.
    order_amount: int

    # Total tax amount of the order. The value should be in non-negative minor units.  Example: 25 Euros should be 2500.
    order_tax_amount: int

    # An array containing list of line items that are part of this order. Maximum of 1000 line items could be processed in a single order.
    order_lines: typing.List[OrderLine]

class OptionalOrder(TypedDict, total=False):
    tags: OrderTags

    # Unique order ID that will be used for the entire lifecycle of the order. (max 255 characters)
    order_id: str

    # The merchant name (max 255 characters).
    name: str

    # The current status of the order. The status will be ‘incomplete’ until the customer has been successfully authorized.
    status: str

    billing_address: Address

    shipping_address: Address

    customer: Customer

    merchant_urls: MerchantUrls

    # The HTML snippet that is used to render the checkout in an iframe.
    html_snippet: str

    # Used for storing merchant's internal order number or other reference. If set, will be shown on the confirmation page as \"order number\" . The value is also available in the settlement files. (max 255 characters). Example: \"45aa52f387871e3a210645d4\"
    merchant_reference1: str

    # Used for storing merchant's internal order number or other reference. The value is available in the settlement files. (max 255 characters). Example: \"45aa52f387871e3a210645d4\"
    merchant_reference2: str

    # ISO 8601 datetime. The date and time when the order has been created. The format will be as follows: \"yyyy-mm-ddThh:mm:ssZ\"
    started_at: datetime

    # ISO 8601 datetime. The date and time when the order has been completed. The format will be as follows: \"yyyy-mm-ddThh:mm:ssZ\"
    completed_at: datetime

    # ISO 8601 datetime. The date and time when the order was last modified. The format will be as follows: \"yyyy-mm-ddThh:mm:ssZ\"
    last_modified_at: datetime

    options: Options

    attachment: Attachment

    # List of external payment methods that will be displayed as part of payment methods in the checkout.
    external_payment_methods: typing.List[PaymentProvider]

    # List of external checkouts that will be displayed as part of payment methods in the checkout. The image_url is required, and the image size has to be 276x48px
    external_checkouts: typing.List[PaymentProvider]

    shipping_countries: OrderShippingCountries

    # A list of shipping options available for this order.
    shipping_options: typing.List[ShippingOption]

    # Pass through field to send any information about the order to be used later for reference while retrieving the order details (max 6000 characters).
    merchant_data: str

    gui: Gui

    merchant_requested: MerchantRequested

    selected_shipping_option: ShippingOption

    # Indicates whether this purchase will create a token that can be used by the merchant to create recurring purchases. This must be enabled for the merchant to use. Default: false  Depending on specified country, recurring could be used for the following payment methods: Pay Later, Direct Debit, Card.
    recurring: bool

    # Token to be used when creating recurring orders.
    recurring_token: str

    # Description to be added to the recurring order.
    recurring_description: str

    billing_countries: OrderBillingCountries

    # List of discounts applied to this order via the KCO discount-service
    discount_lines: typing.List[DiscountLine]

class Order(RequiredOrder, OptionalOrder):
    pass
