# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from klarna_checkout_python_sdk.type.payment_provider_countries import PaymentProviderCountries

class RequiredPaymentProvider(TypedDict):
    # The name of the payment provider. (max 255 characters)
    name: str

    # URL to redirect to. (must be https, min 7, max 2000 characters)
    redirect_url: str

class OptionalPaymentProvider(TypedDict, total=False):
    # Short description of the payment method. This is displayed below the selected payment method. (max 500 characters)
    description: str

    # Minor units. Includes tax.
    fee: int

    countries: PaymentProviderCountries

    # Controls label of buy button<ul><li>continue</li><li>complete</li></ul>
    label: str

    # URL to an image to display. (must be https, max 2000 characters)
    image_url: str

class PaymentProvider(RequiredPaymentProvider, OptionalPaymentProvider):
    pass
