# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from klarna_checkout_python_sdk.type.dimensions import Dimensions
from klarna_checkout_python_sdk.type.shipping_attributes_tags import ShippingAttributesTags

class RequiredShippingAttributes(TypedDict):
    pass

class OptionalShippingAttributes(TypedDict, total=False):
    tags: ShippingAttributesTags

    # The product's weight as used in the merchant's webshop. Non-negative. Measured in grams.
    weight: int

    dimensions: Dimensions

class ShippingAttributes(RequiredShippingAttributes, OptionalShippingAttributes):
    pass
