# coding: utf-8

"""
    Klarna Checkout API V3

    The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSubscription(TypedDict):
    # The cadence unit for this.  Example: \"DAY\"
    interval: str

    # The number of intervals.  Example: 30
    interval_count: int

class OptionalSubscription(TypedDict, total=False):
    # The name of the subscription product.  Example: \"Premium Account\"
    name: str

class Subscription(RequiredSubscription, OptionalSubscription):
    pass
